MICROSOFT_EMAIL = "ENTER YOUR EMAIL ADDRESS"
MICROSOFT_PASSWORD = "ENTER YOUR PASSWORD"
MICROSOFT_LOGIN_URL = "https://login.microsoftonline.com/"
MICROSOFT_FORM_URL = "https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyMh6mdFa-OFBkHsyBFa3fSVUODFSWUZGUU1TSzFGWVFFOE1MSjI1NkhOViQlQCN0PWcu "

MIN_TEMPERATURE = 35.6
MAX_TEMPERATURE = 36.5
STATE_CONST = [False, True, False]

JOB_TIME = "6:00"
