MICROSOFT_LOGIN_URL = "https://login.microsoftonline.com/"
MICROSOFT_FORM_URL = "https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyMh6mdFa-OFBkHsyBFa3fSVUODFSWUZGUU1TSzFGWVFFOE1MSjI1NkhOViQlQCN0PWcu "

MICROSOFT_EMAIL = ""
MICROSOFT_PASSWORD = ""

MIN_TEMPERATURE = 35.6
MAX_TEMPERATURE = 36.5

JOB_TIME = "08:00"
